apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-monitor
  labels:
    release: prometheus  # Must match your Prometheus release
spec:
  selector:
    matchLabels:
      app: my-fastapi-app
  namespaceSelector:
    matchNames:
    - default  # Namespace where FastAPI is deployed
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
